- name: Create and update users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
    password: "{{ item.password | password_hash('sha512') | default(omit) }}"
    state: present
  loop: "{{ users }}"

- name: Install SSH keys
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    state: present
  loop: "{{ users }}"
  when: item.key is defined
