- name: Create and update user
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "{{ user.groups | default(omit) }}"
    shell: "{{ user.shell | default(omit) }}"
    home: "{{ user.home | default(omit) }}"
    password: "{{ user.password | password_hash('sha512') | default(omit) }}"
    state: present

- name: Install SSH key
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    key: "{{ user.key }}"
    state: present
  when: user.key is defined
